meta_product_name: "Le Parc Sauvage"
meta_title: "Le Parc Sauvage"
meta_description: "Le Parc Sauvage"
meta_keywords: "parc zoologique, parc animalier, parc de vision, fauconnerie, ferme pédagogique, Périgord, perigord vert, centre de sauvegarde, lapin, ane, chevre, poule, aigle, faucon, hibou, chouette, cerf, biche, chevreuil, renard, soigneur animalier, spectacle fauconnerie, zoo, animaix, sortie enfants, spectacle enfants"
meta_image: "logo.png"                       # should exist in `app/assets/images/`
twitter_account: ""
