meta_product_name: "Le Parc Sauvage"
meta_title: "Le Parc Sauvage"
meta_description: "Le Parc Sauvage"
meta_keywords: "Parc"
meta_image: "logo.png"                       # should exist in `app/assets/images/`
twitter_account: ""
